import { Wifi, Coffee, Bath, Car, Waves, UtensilsCrossed, Timer, Wine } from 'lucide-react';
import images from '../assets';

export const roomPackageData = [
  {
    id: 1,
    name: 'Luxury Superior Room',
    description:
      'Experience unparalleled comfort in our Luxury Superior Room, featuring premium amenities including a plush king-size bed, marble bathroom with rainfall shower, and panoramic views. Designed for discerning travelers seeking a sophisticated retreat with exceptional service.',
    facilities: [
      { name: 'High-Speed WiFi', icon: Wifi },
      { name: 'Premium Coffee Service', icon: Coffee },
      { name: 'Luxury Bath Amenities', icon: Bath },
      { name: 'Valet Parking', icon: Car },
      { name: 'Swimming Pool Access', icon: Waves },
      { name: 'Daily Breakfast Included', icon: UtensilsCrossed },
      { name: 'Fitness Center Access', icon: Timer },
      { name: 'Complimentary Drinks', icon: Wine },
    ],
    size: 30,
    maxPerson: 1,
    price: 115,
    image: images.Room1Img,
    imageLg: images.Room1ImgLg,
  },
  {
    id: 2,
    name: 'Executive Signature Room',
    description:
      'Our Executive Signature Room offers an elevated experience with bespoke furnishings, a separate living area, and exclusive access to our concierge services. Designed for business travelers and discerning guests seeking premium comfort and personalized service.',
    facilities: [
      { name: 'High-Speed WiFi', icon: Wifi },
      { name: 'Premium Coffee Service', icon: Coffee },
      { name: 'Luxury Bath Amenities', icon: Bath },
      { name: 'Valet Parking', icon: Car },
      { name: 'Swimming Pool Access', icon: Waves },
      { name: 'Daily Breakfast Included', icon: UtensilsCrossed },
      { name: 'Fitness Center Access', icon: Timer },
      { name: 'Complimentary Drinks', icon: Wine },
    ],
    size: 70,
    maxPerson: 2,
    price: 220,
    image: images.Room2Img,
    imageLg: images.Room2ImgLg,
  },
  {
    id: 3,
    name: 'Family Deluxe Room',
    description:
      'The Family Deluxe Room provides exceptional comfort with a spacious layout, modern décor, and superior amenities. Perfect for families or extended stays, featuring a comfortable seating area, well-equipped workspace, and a luxurious bathroom with premium toiletries.',
    facilities: [
      { name: 'High-Speed WiFi', icon: Wifi },
      { name: 'Premium Coffee Service', icon: Coffee },
      { name: 'Luxury Bath Amenities', icon: Bath },
      { name: 'Valet Parking', icon: Car },
      { name: 'Swimming Pool Access', icon: Waves },
      { name: 'Daily Breakfast Included', icon: UtensilsCrossed },
      { name: 'Fitness Center Access', icon: Timer },
      { name: 'Complimentary Drinks', icon: Wine },
    ],
    size: 50,
    maxPerson: 3,
    price: 265,
    image: images.Room3Img,
    imageLg: images.Room3ImgLg,
  },
  {
    id: 4,
    name: 'Premium Luxury Room',
    description:
      'Indulge in our Premium Luxury Room, featuring sophisticated design, premium furnishings, and top-tier amenities. Includes a plush seating area, elegant décor, and a spa-like bathroom with deep soaking tub for the ultimate relaxation experience.',
    facilities: [
      { name: 'High-Speed WiFi', icon: Wifi },
      { name: 'Premium Coffee Service', icon: Coffee },
      { name: 'Luxury Bath Amenities', icon: Bath },
      { name: 'Valet Parking', icon: Car },
      { name: 'Swimming Pool Access', icon: Waves },
      { name: 'Daily Breakfast Included', icon: UtensilsCrossed },
      { name: 'Fitness Center Access', icon: Timer },
      { name: 'Complimentary Drinks', icon: Wine },
    ],
    size: 50,
    maxPerson: 4,
    price: 289,
    image: images.Room4Img,
    imageLg: images.Room4ImgLg,
  },
  {
    id: 5,
    name: 'Luxury Suite',
    description:
      'Our Luxury Suite offers expansive living space with separate bedroom and living areas, kitchenette, and private balcony with stunning views. Designed for extended business or leisure stays with premium amenities throughout.',
    facilities: [
      { name: 'High-Speed WiFi', icon: Wifi },
      { name: 'Premium Coffee Service', icon: Coffee },
      { name: 'Luxury Bath Amenities', icon: Bath },
      { name: 'Valet Parking', icon: Car },
      { name: 'Swimming Pool Access', icon: Waves },
      { name: 'Daily Breakfast Included', icon: UtensilsCrossed },
      { name: 'Fitness Center Access', icon: Timer },
      { name: 'Complimentary Drinks', icon: Wine },
    ],
    size: 90,
    maxPerson: 5,
    price: 320,
    image: images.Room5Img,
    imageLg: images.Room5ImgLg,
  },
  {
    id: 6,
    name: 'Presidential Suite',
    description:
      'Experience unparalleled elegance in our Presidential Suite, featuring custom Italian furniture, Egyptian cotton linens, and a spa-inspired bathroom with a rainfall shower and soaking tub. Includes a private terrace with breathtaking views and dedicated concierge service.',
    facilities: [
      { name: 'High-Speed WiFi', icon: Wifi },
      { name: 'Premium Coffee Service', icon: Coffee },
      { name: 'Luxury Bath Amenities', icon: Bath },
      { name: 'Valet Parking', icon: Car },
      { name: 'Swimming Pool Access', icon: Waves },
      { name: 'Daily Breakfast Included', icon: UtensilsCrossed },
      { name: 'Fitness Center Access', icon: Timer },
      { name: 'Complimentary Drinks', icon: Wine },
    ],
    size: 84,
    maxPerson: 7,
    price: 389,
    image: images.Room7Img,
    imageLg: images.Room7ImgLg,
  },
];